### ISSUE TITLE
Dex Build In samsung-cnct Needed

### ISSUE THREAD

**Issue by mikeln** [samsung-cnct/k2-charts#101]
dex is currently under keyolk's private quay.io repo.  It should be built by samsung-cnct and stored in the project repo instead.

**Comment by coffeepac** [comment]
@joejulian are you dealing with this?

**Comment by joejulian** [comment]
yes

**Comment by coffeepac** [comment]
assigning to @joejulian and setting an arbitrary priority so it stops coming up in my queries.

**Comment by joejulian** [comment]
Now installing from quay.io/coreos/dex
