### ISSUE TITLE
Split Dex & DexApp into separate charts

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2-charts#106]
Currently Dex and DexApp are deployed with the same chart.  Dex does not require DexApp and in fact we should be using something different less onerous then DexApp.

This ticket should focus on splitting these two applications into their own charts.

**Comment by joejulian** [comment]
This will be addressed with the work that @venezia is doing moving these into their own repo.

**Comment by coffeepac** [comment]
@joejulian can I get some issues for the work he's doing or is this not being tracked in github?
