### ISSUE TITLE
add option to charts for tolerations

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/k2-charts#112]
add to values.yaml: 
```  tolerations:
#  - key: iamataintkey
#    value: taintvalue
#    operator: iamataintoperator
#    effect: NoSchedule
```
and then to relevant configs, either: 
```
      tolerations:
      {{- range .Values.scheduling.tolerations }}
      - key: {{ .key }}
        value: {{ .value }}
        operator: Equal
        effect: {{ .effect }}
      {{- end }}
      {{- end }}
```

or : 
```
{{- if .Values.tolerations }}
       tolerations:
 {{ toYaml .Values.tolerations | indent 8 }}
 {{- end}}
```

**Comment by leahnp** [comment]
@DStorck should this be added to all charts? I have to research if we need to add tolerations to the future logging solutions, so this is helpful for me to understand the big picture.

**Comment by DStorck** [comment]
@leahnp It needs to get added to any chart that has a daemonset, pod, deployment, statefulSet, or replica controller....basically pods and things that create pods. For logging it will affect probably just daemonsets, but I have an open [PR](https://github.com/samsung-cnct/k2-charts/pull/111) to add masterNode toleration to daemonsets.

**Comment by DStorck** [comment]
work is done here: https://github.com/samsung-cnct/k2-charts/pull/114

**Comment by leahnp** [comment]
LGTM
