### ISSUE TITLE
Create logging-lite chart from solas-chart

### ISSUE THREAD

**Issue by leahnp** [samsung-cnct/k2-charts#120]
Create logging-lite Helm Chart (fluent-bit -> elasticsearch)

- [x] Following the instructions at https://github.com/samsung-cnct/solas-container, create a new repo named chart-xxx

- [x] Create a chart

- [x] Verify the Jenkinsfile in the repo tags an app and uploads it to quay.io

**Comment by leahnp** [comment]
See conversation: https://github.com/samsung-cnct/k2-charts/issues/119

**Comment by guineveresaenger** [comment]
As per discussion [here](https://github.com/samsung-cnct/chart-elasticsearch/issues/3), please use https://github.com/samsung-cnct/chart-elasticsearch for dependency.

**Comment by DStorck** [comment]
How are users going to get access to their data? an ELB? or should we be including kibana in this logging-lite to give users an easy way to see their logs?

**Comment by leahnp** [comment]
One vote for including Kibana.

**Comment by DStorck** [comment]
Chart now includes kibana, but there are blockers to getting this to actually run. Here is the main problem: https://github.com/app-registry/appr-helm-plugin/issues/3#issuecomment-302701693

Currently working to vendor the deps and push that to quay

**Comment by DStorck** [comment]
For future reference - I initially set up the chart repo as detail in the above comment ^^, using the `appr` field , but that isn't actually working yet apparently. To make it functional, I had to go into that chart and run `helm registry dep --overwrite`, and then `helm dep build`. That turned my requirements.yaml into something that  `helm registry` could work with. Unfortunately, it built it in a location that was not super useful.  It changed `requirements.yaml`, and also vendored the deps into `appr_charts/`, but that directory needed to get moved into `logging/` along with the `requirements.yaml` and `requirements.lock`.  So for future work, anyone wishing to update this will need to follow those steps of those helm commands, and then moving the created directories into the right place.

**Comment by DStorck** [comment]
To review: 
- fire up a new cluster
- make sure you have the [helm registry plugin](https://github.com/app-registry/appr-helm-plugin#install-the-helm-registry-plugin)
- run `helm registry install quay.io/samsung_cnct/logging`
- run `kubectl get svc kibana-logging -owide`
- go to `<EXTERNAL_IP>:5601`  and verify that you can see your cluster logs

**Comment by leahnp** [comment]
Worked like a charm! Just have to make sure the cluster is big enough and your cluster storage class is correct.
