### ISSUE TITLE
Check/fix daemon-fluentd tolerations

### ISSUE THREAD

**Issue by leahnp** [samsung-cnct/k2-charts#127]
Investigate why and fix the following behavior.

When trying to install the latest version of this chart Helm returned:
```
$  helm upgrade central-logging cnct/central-logging
Error: UPGRADE FAILED: error validating "": error validating data: found invalid field tolerations for v1.PodSpec
```

For now, I have commented out the code I was suspect of and the chart upgrade was successful. 

Resources:
https://github.com/fluent/fluentd-kubernetes-daemonset/issues/38
https://github.com/kubernetes/kubernetes/issues/42983
Check the k8s fluentd deployment to see if we can model their approach to tolerations for daemonsets.

**Comment by DStorck** [comment]
This may be because the prod cluster is 1.5 and tolerations were introduced in their current setup in 1.6.

**Comment by leahnp** [comment]
https://github.com/samsung-cnct/issues/issues/36 < might take care of this

**Comment by coffeepac** [comment]
1.5 is no longer supported by k8s at large (and us soon)
