### ISSUE TITLE
[central-logging] not installing

### ISSUE THREAD

**Issue by Morriz** [samsung-cnct/k2-charts#137]
I get the following error:

```
Error: found in requirements.yaml, but missing in charts/ directory: daemon-fluentd, kafka, central-fluentd, elasticsearch, kibana
```

**Comment by DStorck** [comment]
that chart  is about to be marked as deprecated, thanks for bringing this to our attention. Consider trying out a lighter logging solution at https://github.com/samsung-cnct/chart-logging, which currently works for kubernetes clusters < 1.8

**Comment by coffeepac** [comment]
@Morriz our apologies for this, but this is now a deprecated chart and we do not plan on fixing it.  

as @DStorck mentions, you are welcome to try a lighter-weight logging solution which uses fluentbit & elasticsearch.  if you have any questions or comments about that chart please open an issue there OR find us in kubernetes slack in the #kraken channel.
