### ISSUE TITLE
Fluent-Bit Sidecar Logging Option

### ISSUE THREAD

**Issue by leahnp** [samsung-cnct/k2-charts#40]
Create yaml params that can be added to application that requires logs are captured from a specific directory. Test it works with in_tail Fluentbit and https://github.com/leahnp/fluent-bit-kafka-output-plugin/blob/master/out_kafka.go output plugin.

This would replace FluentD daemonset currently being used in the central logging pipeline.

**Comment by leahnp** [comment]
Fluentbit running in sidecar, sending messages end to end from named directory. Working on a bug with the encoding, may lie in tail input or out kafka plugin.

**Comment by leahnp** [comment]
Current status/MVP: Fluentbit will run in sidecar, next to app you want to pull logs from. It will TAIL in from a specified directory and send logs as JSON to KAFKA, via brokers (currently hardcoded). Does not have metadata support currently - TODO list included in README for plugin.

Sidecar deployment example: https://github.com/leahnp/fluentbit-sidecar/blob/master/fluentbit.yaml
Sidecar Docker image: https://github.com/leahnp/fluentbit-sidecar
Plugin: https://github.com/leahnp/fluent-bit-kafka-output-plugin

**Comment by coffeepac** [comment]
Stellar.
