### ISSUE TITLE
fluentd plugin for handling pod specific directory name

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/k2-charts#42]
full design here: https://hanjin.atlassian.net/wiki/display/CoT/Non-standard+log+file+collection

each pod will have a globally unique directory name in the common logging hostVolume in the format specified in the above wiki page. this plugin should take all of the pieces and add to each outbound record.

**Comment by coffeepac** [comment]
This should include an installable pluging from rubygems.org or some other ruby gem repository.
