### ISSUE TITLE
problem in getting the ElasticSearch StatefulSet to form a cluster

### ISSUE THREAD

**Issue by Analect** [samsung-cnct/k2-charts#48]
Thanks for your work on this. 
I wanted to try out this StatefulSet implementation rather than the 'official' one [here](https://github.com/kubernetes/charts/tree/master/incubator/elasticsearch), which is missing some elements to allow it to work with v 5.x of ES.

I'm wondering if someone might be able to offer guidance on a problem I'm having in getting the ES to form a cluster.

I'm running a 3 node cluster on Google Cloud Platform ... running version 1.5.1 of kubernetes (both master and nodes).

![image](https://cloud.githubusercontent.com/assets/4063815/21566451/103c237a-ce9b-11e6-8bee-da55a73d4c25.png)

I was initially hitting limits, so for testing purposes, I modified the `elasticsearch/values.yaml` to reduce the replicas to 1 for both elasticsearch-master and elasticsearch-data ... and also reduced memory_limits and Xms Xmx settings.
```
master_replicas: 1
master_imagePullPolicy: Always
master_cpu_limits: 500m
master_cpu_requests: 500m
master_memory_limits: 2Gi
master_memory_requests: 2Gi
# master_volume_storage: set to small so when exploring with this the 
# user doesn't accidentally create very large disks
master_volume_storage: 20Gi
# Xms & Xmx: must be the same 
# should be ~75% of total memory allocation
master_Xms_Xmx: 1g
```

I also modifed the `elasticsearch/templates/es.yaml` such that PetSet was replaced by StatefulSet and moved to `apps/v1beta1`.  However, I didn't modify `pod.alpha.kubernetes.io/init-containers` or `volume.alpha.kubernetes.io/storage-class` to beta.

```
apiVersion: apps/v1beta1
kind: StatefulSet
```

Running up `helm install elasticsearch/` appeared to work OK.  Although I can see from the events in both StatefulSets that there was initially a Scheduler problem (see screenshot lower down) due to the pvc not being bound.  However that appears to have fixed itself ... with the relevant pv and pvc resources getting automatically created and bound.

```
kubectl get pv,pvc
NAME                                          CAPACITY   ACCESSMODES   RECLAIMPOLICY   STATUS    CLAIM                                   REASON    AGE
pv/pvc-766c7121-ce93-11e6-abfc-42010a84002e   20Gi       RWO           Delete          Bound     default/esdata-elasticsearch-master-0             1h
pv/pvc-767cc467-ce93-11e6-abfc-42010a84002e   20Gi       RWO           Delete          Bound     default/esdata-elasticsearch-data-0               1h

NAME                                STATUS    VOLUME                                     CAPACITY   ACCESSMODES   AGE
pvc/esdata-elasticsearch-data-0     Bound     pvc-767cc467-ce93-11e6-abfc-42010a84002e   20Gi       RWO           1h
pvc/esdata-elasticsearch-master-0   Bound     pvc-766c7121-ce93-11e6-abfc-42010a84002e   20Gi       RWO           1h

```

![image](https://cloud.githubusercontent.com/assets/4063815/21566461/242ca454-ce9b-11e6-9e70-fd04d4d72331.png)

If I run `kubectl port-forward elasticsearch-master-0 9200:9200` and navigate to `localhost:9200` in my browser, I can confirm that the master ES node is there.

![image](https://cloud.githubusercontent.com/assets/4063815/21566439/fb505f8a-ce9a-11e6-8ce3-70f8e24e1f48.png)

However, it appears that the ES cluster is not forming properly and perhaps that is related to either the 'elasticsearch' or 'elasticsearch-cluster' not forming properly, since I see both have a CLUSTER-IP set to none.

```
kubectl get svc
NAME                    CLUSTER-IP   EXTERNAL-IP   PORT(S)    AGE
elasticsearch           None         <none>        9200/TCP   1h
elasticsearch-cluster   None         <none>        9300/TCP   1h
kubernetes              10.7.240.1   <none>        443/TCP    1d
```

Could this be the reason that master and data nodes are not able to find eachother?

sample logs from elasticsearch-master-0
```
[2016-12-30T13:27:25,491][INFO ][i.f.e.d.k.KubernetesUnicastHostsProvider] [elasticsearch-master-0] adding endpoint /10.4.3.4, transport_address 10.4.3.4:9300
[2016-12-30T13:27:26,504][WARN ][o.e.n.Node               ] [elasticsearch-master-0] timed out while waiting for initial discovery state - timeout: 30s
[2016-12-30T13:27:26,596][INFO ][o.e.h.HttpServer         ] [elasticsearch-master-0] publish_address {10.4.4.3:9200}, bound_addresses {0.0.0.0:9200}
[2016-12-30T13:27:26,596][INFO ][o.e.n.Node               ] [elasticsearch-master-0] started
[2016-12-30T13:27:27,095][INFO ][i.f.e.d.k.KubernetesUnicastHostsProvider] [elasticsearch-master-0] adding endpoint /10.4.3.4, transport_address 10.4.3.4:9300
[2016-12-30T13:27:27,108][INFO ][i.f.e.d.k.KubernetesUnicastHostsProvider] [elasticsearch-master-0] adding endpoint /10.4.3.4, transport_address 10.4.3.4:9300
[2016-12-30T13:27:28,697][INFO ][i.f.e.d.k.KubernetesUnicastHostsProvider] [elasticsearch-master-0] adding endpoint /10.4.3.4, transport_address 10.4.3.4:9300
```

sample logs from elasticsearch-data-0
```
[i.f.e.d.k.KubernetesUnicastHostsProvider] [elasticsearch-data-0] adding endpoint /10.4.4.3, transport_address 10.4.4.3:9300
2016-12-30T13:27:25.515536043Z [2016-12-30T13:27:25,515][INFO ][i.f.e.d.k.KubernetesUnicastHostsProvider] [elasticsearch-data-0] adding endpoint /10.4.4.3, transport_address 10.4.4.3:9300
2016-12-30T13:27:27.033487290Z [2016-12-30T13:27:27,033][INFO ][i.f.e.d.k.KubernetesUnicastHostsProvider] [elasticsearch-data-0] adding endpoint /10.4.4.3, transport_address 10.4.4.3:9300
2016-12-30T13:27:27.706667393Z [2016-12-30T13:27:27,706][WARN ][o.e.n.Node               ] [elasticsearch-data-0] timed out while waiting for initial discovery state - timeout: 30s
2016-12-30T13:27:27.802438637Z [2016-12-30T13:27:27,802][INFO ][o.e.h.HttpServer         ] [elasticsearch-data-0] publish_address {10.4.3.4:9200}, bound_addresses {0.0.0.0:9200}
2016-12-30T13:27:27.802831216Z [2016-12-30T13:27:27,802][INFO ][o.e.n.Node               ] [elasticsearch-data-0] started
2016-12-30T13:27:28.599036539Z [2016-12-30T13:27:28,598][INFO ][i.f.e.d.k.KubernetesUnicastHostsProvider] [elasticsearch-data-0] adding endpoint /10.4.4.3, transport_address 10.4.4.3:9300
```
I would very much appreciate some guidance in troubleshooting this.
Also, what setting might I add in order to expose port 9200 externally, so I can more easily test ES without port-forwarding?

**Comment by coffeepac** [comment]
@Analect sorry for not getting to this yesterday, I started vacation a day early.  I'll be back in my office on Tuesday, Jan 3rd.  

Quick notes though:
1. the pvc error you saw that resolved itself is expected.  the pod gets created faster then k8s + gcloud can allocate a PD.  you'll see that log message often if you spend time using pvc templates.
2. the missing ClusterIP isn't a problem.  those are 'headless services' where k8s will use the svc entry for load balancing across the selected pods
3. the thing to check is the endpoint list for the two elasticsearch services.  if there are no endpoints listed there is something wrong with the service selector value.  you can check the endpoint list by running 'kubectl describe service elasticsearch'.  Endpoints are one of the fields
4. to expose elasticsearch on 9200 externally you can change the 'Type' of the elasticsearch-data service to be LoadBalancer.  For gcloud that will create a ForwardingRule in gcloud which will have an externally visible address.  Or an ingress controller to k8s and use the controller.  

Thank you for making the change to StatefulSets locally.  If you want to PR your change back that'd be great and if not we have a couple other PetSet -> StatefulSet transitions to make so no worries.

**Comment by coffeepac** [comment]
@Analect to clarify a bit more, the elasticsearch-cluster is the service that is used for cluster formation and management so that is the service to check for membership in the Endpoints field.  That service should have all elasticsearch pods.  

the elasticsearch service is for elasticsearch data and is what clients will connect to.

I'm also a bit surprised that the elasticsearch nodes are coming up with only 1GB of memory allocated to the JVM, I thought (probably wrongly) that es 5.0 had a startup check that required more memory then that.  Can you provide a larger log sample from the master pod?  There should be something useful in there.  also, can you check to see if the master pod is restarting?

**Comment by Analect** [comment]
@coffeepac 
Thanks for your response.  Let me retry and report back.

**Comment by coffeepac** [comment]
@Analect any luck with getting through this for now?  

@DStorck as part of the conversion issue can you do the ES cluster first?  it'll help us out here.

**Comment by DStorck** [comment]
We are currently running this in aws us-east-1 with 6 m4.xlarge clusterNodes, 3 m3.medium masterNodes, and bringing up the whole system using the central-logging chart found here: https://github.com/samsung-cnct/k2-charts/tree/master/central-logging.  Everything is up and running.

**Comment by coffeepac** [comment]
@Analect we've upgraded our charts to be StatefulSets instead of PetSets.  Can you give them another shot?  We were able to get ES clusters up and running.

**Comment by coffeepac** [comment]
haven't heard back from @Analect.  will happily re-open if he returns with more info.

**Comment by Analect** [comment]
Sorry @coffeepac ... for not responding sooner.
Working with your set-up now ... just 1 master and 2 data ... and added in a kibana.  Appears to work well. 

I just wanted to get your insights on whether you've experimented with mechanisms such as the hook below to manage scaling up/down data nodes for ES.
see: https://github.com/mrmm/elasticsearch-kubernetes/blob/master/pre-stop-hook.sh

This is a pre-stop-hook.sh script, derived from here: https://github.com/jetstack/elasticsearch-pet/blob/master/pre-stop-hook.sh
It is intended to handle downscales so that no data loss occurs (using lifecycle hooks)
It makes a call to the kubernetes API, then uses jq to parse .. and ultimately transfer data pertaining to ES from a node before it is closed.  I don't fully understand the implementation .. it also needs updating as the API has changed ... see https://github.com/jetstack/elasticsearch-pet/issues/2.

Anyway, thought I would ask here given you an your colleagues appear to have good experience in this space.

**Comment by coffeepac** [comment]
@Analect no worries about the slow response!  I've just got a big board of tickets and if they go stale I like to keep the board clear. 

I haven't used that hook at all although it is interesting looking.  We considered trying to pull it into our chart but scale up and scale down events for ES are not terribly common under normal operating modes so we punted until we had a solid use case for it.

One thing we should do, and I'll go file a ticket for it now, is to include [curator](https://github.com/elastic/curator) as part of this config.  Curator is an elastic product and performs basic maintenance on your cluster to keep it performant and to use minimal resources.
