### ISSUE TITLE
convert PetSets to stateful sets

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2-charts#49]
K2 is moving from kubernetes 1.4 to 1.5.  PetSets have gone away and are replaced by StatefulSets.  Convert, at least, kafka, zookeeper and elasticsearch.

**Comment by DStorck** [comment]
https://kubernetes.io/docs/tasks/manage-stateful-set/upgrade-pet-set-to-stateful-set/

**Comment by DStorck** [comment]
In the future we could use a helm hook to let helm check k8s version and then decide which chart to  bring up from there, but might be unnecessary at this point since petset was booted while still alpha. https://github.com/kubernetes/helm/blob/master/docs/charts_hooks.md

**Comment by DStorck** [comment]
updated all configuration files in central-logging that included petsets.  changed api version and kind , as well as removed annotation pod.alpha.kubernetes.io/initialized in accordance with k8s official recommendation.  Pods are coming up alright but i'm experiencing trouble potentially related to https://github.com/samsung-cnct/k2-charts/issues/48

**Comment by davidewatson** [comment]
Can we also convert prometheus?

**Comment by DStorck** [comment]
I sure can, Patrick had wanted me to just get started on the logging files but Im happy to do Prometheus as well.

**Comment by davidewatson** [comment]
Awesome. Besides the name of the kafka image repository, I think that one line change completes the migration of charts to k8s 1.5...

```
rodin:k2-charts dwat$ grep -ri petset .
./central-logging/README.md:* Image: https://quay.io/repository/samsung_cnct/kafka-petset
./kafka/values.yaml:image: quay.io/samsung_cnct/kafka-petset:0.1
./prometheus/templates/statefulset.yaml:kind: PetSet
rodin:k2-charts dwat$ 
```

**Comment by DStorck** [comment]
Should i upgrade to version 0.3.0?

**Comment by coffeepac** [comment]
got these running on my own.  off to done.
