### ISSUE TITLE
include elastic curator as part of elasticsearch chart

### ISSUE THREAD

**Issue by coffeepac** [samsung-cnct/k2-charts#63]
as discussed in #48 we should be using curator with some sane defaults for length of time to keep indexes open, around and how often to run cleanup operations.

**Comment by coffeepac** [comment]
@leahnp take a look!  put back to p2 if needed.

**Comment by DStorck** [comment]
moved to issues. ( dupe of https://github.com/samsung-cnct/elasticsearch-kubernetes/issues/8)
