### ISSUE TITLE
Remove prometheus and grafana charts

### ISSUE THREAD

**Issue by davidewatson** [samsung-cnct/k2-charts#82]
There are existing publicly maintained versions of these charts which are better than our. There are no known Samsung specific changes, so it would reduce our maintenance overhead, and improve usability, if we removed these charts. A note should be left in the README.md for each chart directing users to the new charts.

**Comment by ringods** [comment]
Try using official Helm deprecation:

https://github.com/kubernetes/helm/blob/master/docs/charts.md#deprecating-charts

**Comment by leahnp** [comment]
LGTM addressed by: https://github.com/samsung-cnct/k2-charts/pull/87
