### ISSUE TITLE
K8s 1.6 chart changes

### ISSUE THREAD

**Issue by alejandroEsc** [samsung-cnct/k2-charts#91]
Those charts that will be part of a 1.6 k8s cluster need to be updated if they require particular permissions to run. For example fluentd needs:

-serviceAccount 
- clusterRole defined (or a default used)
- clusterRoleBinding. 

I assume other charts need similar work in place, So i suggest this issue be a ticket referenced by per-chart-issues to be opened and this closed when all of those charts have been resolved.

**Comment by leahnp** [comment]
I think @DStorck was looking into this here: https://github.com/samsung-cnct/k2/issues/361

**Comment by coffeepac** [comment]
blocked by not having a k2-tools CI build process

**Comment by coffeepac** [comment]
this will be handled naturally as we port all k2-charts (currently top issue in backlog)
