### ISSUE TITLE
references to petset should be edited

### ISSUE THREAD

**Issue by DStorck** [samsung-cnct/k2-charts#95]
we have several places where petsets are mentioned , these can all updated to stateful sets to it is clear that we have updated our work

- https://github.com/samsung-cnct/kafka-kubernetes
- https://quay.io/repository/samsung_cnct/kafka-petset
- references to kafka-petset repo in https://github.com/samsung-cnct/k2-charts/blob/master/kafka/values.yaml

**Comment by coffeepac** [comment]
@leahnp cleanup for logging
